### ISSUE TITLE
Giving error in code

### ISSUE THREAD

**Issue by Apoorv012** [issamelferkh/userrecon#12]
I am trying to run this code in Windows using WSL - Arch. It gives the following error:
```
main.sh: line 5: $'\r': command not found
main.sh: line 6: trap: 2
: invalid signal specification
main.sh: line 7: $'\r': command not found
main.sh: line 8: syntax error near unexpected token `$'{\r''
main.sh: line 8: `banner() {
'

[Execution complete with exit code 2]
```
I don't know Bash. Can you look into this problem? Thanks.

**Comment by Apoorv012** [comment]
Ok, I will try. Thanks :)

**Comment by issamelferkh** [comment]
Your welcome, please let me know if it works for you.

**Comment by Apoorv012** [comment]
I tried to run this on VirtualBox, and it worked like a charm. Great work 👍!
